version: '2'
volumes:
  database-data:
services:
  motion-detector:
    build: ./motion-detector
    restart: always
    privileged: true
  browser-display:
    build: ./browser-display
    restart: always
    privileged: true
    environment:
      - WPE_URL=http://ui-server:3000
    links:
      - ui-server
    depends_on:
      - ui-server
    ports:
      - 8080:8080
  ui-server:
    build: ./ui-server
    restart: always
    ports:
      - 3000:3000
  beer-db:
    build: ./beers-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
