version: '2'
services:
  app:
    build: ./app
    restart: always
    privileged: true
    ports:
      - 80:80
  wpe:
    build: ./wpe
    restart: always
    privileged: true
    links:
      - app
    ports:
      - 8080:8080
