version: '2'
services:
  motion-detector:
    build: ./motion-detector
    restart: always
    privileged: true
  browser-display:
    build: ./browser-display
    restart: always
    privileged: true
    environment:
      - WPE_URL=http://ui:3000
    links:
      - ui
    depends_on:
      - ui
    ports:
      - 8080:8080
  ui:
    build: ./ui
    restart: always
    ports:
      - 3000:3000
