version: '2'
services:
  app:
    build: ./app
    restart: always
    privileged: true
    ports:
      - 8080:8080
  wpe:
    build: ./wpe
    restart: always
    privileged: true
    environment:
      - WPE_URL="http://app:8080/"
    links:
      - app
    depends_on:
      - app
