version: '2'
services:
  app:
    build: ./app
    restart: always
    privileged: true
    ports:
      - 3000:3000
  wpe:
    build: ./wpe
    restart: always
    privileged: true
    environment:
      - WPE_HOST_AND_PORT=app:3000
      - WPE_URL=http://app:3000
    links:
      - app
    depends_on:
      - app
    ports:
      - 8080:8080
