FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-run
MAINTAINER Jeremy White <jeremy.ro.white@gmail.com>

RUN install_packages build-essential pigpio python

WORKDIR /usr/src/app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*

COPY . .

ENV UDEV=1

CMD ["npm", "start"]
