FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-build AS build
MAINTAINER Jeremy White <jeremy.ro.white@gmail.com>

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*

FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-run

WORKDIR /usr/src/app

COPY --from=build node_modules node_modules

CMD ["npm", "start"]
